---
- name: setup workstation
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Add the flathub flatpak repository
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install flatpak packages
    flatpak:
      remote: flathub
      name:
        - com.github.IsmaelMartinez.teams_for_linux
        - io.github.dvlv.boxbuddyrs
        - io.gitlab.librewolf-community
        - md.obsidian.Obsidian
        - org.flameshot.Flameshot
        - org.gimp.GIMP
        - org.gnome.Evolution
        - org.onlyoffice.desktopeditors
        - org.remmina.Remmina

  - name: Overlay packages
    community.general.rpm_ostree_pkg:
      name:
        - btop
        - distrobox
        - eza
        - fastfetch
        - tmux
        - vim
      state: present

  - name: Copy wallpaper file
    copy:
      src: files/ublue.png
      dest: /var/home/ryan/.local/share/backgrounds/ublue.png
      owner: root
      group: root

  - name: Set wallpaper
    become_user: ryan
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///var/home/ryan/.local/share/backgrounds/ublue.png'"

  - name: Set wallpaper position
    become_user: ryan
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

