---
- name: setup workstation
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Overlay packages
    community.general.rpm_ostree_pkg:
      name:
        - eza
        - btop
        - tmux
        - vim
      state: present

