---
- name: setup workstation
  hosts: localhost
  connection: local
  become: true

  tasks:
  - name: Overlay packages
    community.general.rpm_ostree_pkg:
      name:
        - htop
        - ranger
        - eza
      state: present

